<?php
namespace App\Helpers;

/**
 * Create this class in its namespace
 * Then add an alias to /config/app.php
 * 'Helper' => App\Helpers\Helper::class,
 */

class Helper
{
    public static function getEventTypes () {
        return ['Cérémonie', 'Concert', 'Festival', 'Showcase', 'Soirée de gala', 'Soirée privée', 'Sortie en boite', 'Spectacle'];
    }


    public static function getCountries () {
        return [
            "Afrique du Sud",
            "Afghanistan",
            "Albanie",
            "Algérie",
            "Allemagne",
            "Andorre",
            "Angola",
            "Antigua-et-Barbuda",
            "Arabie Saoudite",
            "Argentine",
            "Arménie",
            "Australie",
            "Autriche",
            "Azerbaidjan",
            "Bahamas",
            "Bahrein",
            "Bangladesh",
            "Barbade",
            "Belgique",
            "Belize",
            "Benin",
            "Bhoutan",
            "Bielorussie",
            "Birmanie",
            "Bolivie",
            "Bosnie-Herzegovine",
            "Botswana",
            "Brésil",
            "Brunei",
            "Bulgarie",
            "Burkina Faso",
            "Burundi",
            "Cambodge",
            "Cameroun",
            "Canada",
            "Cap-Vert",
            "Chili",
            "Chine",
            "Chypre",
            "Colombie",
            "Comores",
            "Corée du Nord",
            "Corée du Sud",
            "Costa Rica",
            "Côte d'Ivoire",
            "Croatie",
            "Cuba",
            "Danemark",
            "Djibouti",
            "Dominique",
            "Egypte",
            "Emirats arabes unis",
            "Equateur",
            "Erythree",
            "Espagne",
            "Estonie",
            "Etats-Unis",
            "Ethiopie",
            "Fidji",
            "Finlande",
            "France",
            "Gabon",
            "Gambie",
            "Georgie",
            "Ghana",
            "Grece",
            "Grenade",
            "Guatemala",
            "Guinée",
            "Guinée Equatoriale",
            "Guinée-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hongrie",
            "Iles Cook",
            "Iles Marshall",
            "Inde",
            "Indonesie",
            "Irak",
            "Iran",
            "Irlande",
            "Islande",
            "Israel",
            "Italie",
            "Jamaique",
            "Japon",
            "Jordanie",
            "Kazakhstan",
            "Kenya",
            "Kirghizistan",
            "Kiribati",
            "Kosovo",
            "Koweit",
            "Laos",
            "Lesotho",
            "Lettonie",
            "Liban",
            "Liberia",
            "Libye",
            "Liechtenstein",
            "Lituanie",
            "Luxembourg",
            "Macedoine",
            "Madagascar",
            "Malaisie",
            "Malawi",
            "Maldives",
            "Mali",
            "Malte",
            "Maroc",
            "Maurice",
            "Mauritanie",
            "Mexique",
            "Moldavie",
            "Monaco",
            "Mongolie",
            "Montenegro",
            "Mozambique",
            "Namibie",
            "Nauru",
            "Nepal",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norvege",
            "Nouvelle-Zelande",
            "Oman",
            "Ouganda",
            "Ouzbekistan",
            "Pakistan",
            "Palaos",
            "Palestine",
            "Panama",
            "Papouasie-Nouvelle-Guinee",
            "Paraguay",
            "Pays-Bas",
            "Perou",
            "Philippines",
            "Pologne",
            "Portugal",
            "Qatar",
            "Republique centrafricaine",
            "Republique democratique du Congo",
            "Republique Dominicaine",
            "Republique du Congo",
            "Republique Tcheque",
            "Roumanie",
            "Royaume Uni",
            "Russie",
            "Rwanda",
            "Saint-Kitts-et-Nevis",
            "Saint-Vincent-et-les-Grenadines",
            "Sainte-Lucie",
            "Saint-Marin",
            "Salomon",
            "Salvador",
            "Samoa",
            "Sao Tome-et-Principe",
            "Senegal",
            "Serbie",
            "Seychelles",
            "Sierra Leone",
            "Singapour",
            "Slovaquie",
            "Slovenie",
            "Somalie",
            "Soudan",
            "Soudan du Sud",
            "Sri Lanka",
            "Suede",
            "Suisse",
            "Suriname",
            "Swaziland",
            "Syrie",
            "Tadjikistan",
            "Tanzanie",
            "Tchad",
            "Thailande",
            "Timor oriental",
            "Togo",
            "Tonga",
            "Trinite-et-Tobago",
            "Tunisie",
            "Turkmenistan",
            "Turquie",
            "Tuvalu",
            "Ukraine",
            "Uruguay",
            "Vanuatu",
            "Vatican",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambie",
            "Zimbabwe"
        ];
    }
}
